"""add time to post

Revision ID: 657ffcd323df
Revises: 68f3b1762f58
Create Date: 2023-03-18 00:10:22.422747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '657ffcd323df'
down_revision = '68f3b1762f58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_post_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_timestamp'))
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
