"""add language to user

Revision ID: e440a6a87460
Revises: 95fcec0ffdab
Create Date: 2023-03-22 15:00:45.227937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e440a6a87460'
down_revision = '95fcec0ffdab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('language',
               existing_type=sa.VARCHAR(length=2),
               nullable=False, server_default='en')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('language',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)

    # ### end Alembic commands ###
